import './style.css';
import './a11y.css';

const sampleFlags = [
  { key: 'checkout-v2', owner: 'Mina', expiry: '2026-12-01', status: 'Tracked', refs: ['src/checkout.ts:2'] },
  { key: 'legacy-cart', owner: 'Drew', expiry: '2026-02-15', status: 'Expired', refs: ['src/checkout.ts:6', 'src/legacy.ts:1'] },
  { key: 'billing-surge-cap', owner: 'Inez', expiry: '2026-10-01', status: 'Tracked', refs: [] }
];
const app = document.querySelector('#app');
const routes = { '/': home, '/demo': demo, '/privacy': privacy, '/terms': terms, '/404.html': missing };

function nav() { return `<header><a class="mark" href="/" data-route><span aria-hidden="true">✣</span> Flag Stale Guard</a><nav aria-label="Main navigation"><a href="/demo" data-route>Demo</a><a href="/#how">How it works</a><a href="/privacy" data-route>Privacy</a></nav></header>`; }
function foot() { return `<footer><p>Local checks for release flags that outlive their plan.</p><p><a href="/privacy" data-route>Privacy</a> · <a href="/terms" data-route>Terms</a> · Built by Param Factory · v0.1.0</p></footer>`; }
function heroArt() { return `<figure class="hero-art"><img src="/field-guide-hero.webp" width="1200" height="800" fetchpriority="high" alt="Pressed green and dried red leaves on a field-guide page, representing active and expired flags." /><figcaption>Specimen sheet 01 · inspect before removal</figcaption></figure>`; }
function home() { return `${nav()}<main id="main" tabindex="-1"><section class="hero"><div><p class="eyebrow">A local CLI for release flag cleanup</p><h1>Find flags ready for removal</h1><p class="lede">For maintainers who need to remove old flags without leaving live references behind.</p><p class="actions"><a class="button" href="/demo" data-route>Try it with sample data</a><span>See an expired flag and its call sites.</span></p><ul class="facts"><li>Runs in your repository.</li><li>Sends no source code away.</li><li>Free and open source.</li></ul></div>${heroArt()}</section><section class="terminal-wrap" aria-labelledby="preview-title"><div class="section-label"><p class="eyebrow">Sample scan</p><h2 id="preview-title">See the removal gate before install</h2></div><pre class="terminal"><code><span class="prompt">$</span> flag-stale-guard scan --config flag-stale-guard.toml --check

legacy-cart — <b>expired</b>
  owner: Drew | expiry: 2026-02-15
  live references: 2
    src/checkout.ts:6
    src/legacy.ts:1
  removal checklist:
    - Remove every live reference listed below.

<span class="warn">Exit 2: expired flags need attention.</span></code></pre></section><section id="how" class="steps" aria-labelledby="how-title"><div><p class="eyebrow">How it works</p><h2 id="how-title">Keep flag cleanup honest</h2></div><ol><li><b>List each flag.</b><span>Add an owner and ISO expiry in one TOML file.</span></li><li><b>Scan configured paths.</b><span>See literal source references for every known flag.</span></li><li><b>Check before removal.</b><span>Get a checklist after expiry. Block removal while references remain.</span></li></ol></section><section class="limits" aria-labelledby="limits-title"><p class="eyebrow">Clear limits</p><h2 id="limits-title">What Flag Stale Guard does not decide</h2><p>It finds configured source references. It does not evaluate flags, target users, or prove runtime safety.</p><p>Review the checklist and your tests before deleting a flag.</p></section><section class="install" aria-labelledby="install-title"><p class="eyebrow">Install</p><h2 id="install-title">Run it in a repository</h2><pre><code>cargo install flag-stale-guard
flag-stale-guard scan --config flag-stale-guard.toml --check</code></pre><a href="https://github.com/B-Divyesh/sf-flag-stale-guard" rel="external">Read the repository on GitHub</a></section></main>${foot()}`; }
function demo() { return `${nav()}<main id="main" tabindex="-1"><div class="demo-banner" role="status"><span><b>Demo</b> — sample data, nothing is saved.</span><span><button id="reset">Reset demo</button><a href="/" data-route>Start for real</a></span></div><section class="demo-head"><p class="eyebrow">Sample repository scan</p><h1>Inspect three configured flags</h1><p class="lede">One flag expired. Its removal stays blocked until both source references disappear.</p></section><section class="inventory" aria-labelledby="inventory-title"><h2 id="inventory-title">Flag inventory</h2><div id="flag-list">${sampleFlags.map(flagCard).join('')}</div></section><section class="check-panel" aria-labelledby="check-title"><p class="eyebrow">Removal check</p><h2 id="check-title">legacy-cart is blocked</h2><p>Two live references remain in the configured sample paths.</p><ul><li><code>src/checkout.ts:6</code></li><li><code>src/legacy.ts:1</code></li></ul><p class="notice">Next: remove both references, then run <code>flag-stale-guard remove-check legacy-cart</code>.</p></section><section class="demo-command" aria-labelledby="command-title"><h2 id="command-title">Run the same sample locally</h2><pre><code>cargo run -- demo
cargo run -- remove-check legacy-cart --config examples/flag-stale-guard.toml</code></pre></section></main>${foot()}`; }
function flagCard(f) { const status = f.status === 'Expired' ? 'danger' : 'good'; return `<article class="flag ${status}"><div><h3>${f.key}</h3><p>Owner: ${f.owner} · Expires: ${f.expiry}</p></div><div><span class="status">${f.status}</span><p>${f.refs.length} source reference${f.refs.length === 1 ? '' : 's'}</p></div></article>`; }
function legal(title, content) { return `${nav()}<main id="main" tabindex="-1" class="prose"><p class="eyebrow">Flag Stale Guard</p><h1>${title}</h1>${content}</main>${foot()}`; }
function privacy() { return legal('Privacy for local flag checks', '<p>Flag Stale Guard does not collect analytics or send source code to a service.</p><p>The CLI reads only the paths you configure. The website demo uses fixed sample data in your browser and does not store it.</p><p>There are no accounts, payments, or cookies.</p>'); }
function terms() { return legal('Terms for Flag Stale Guard', '<p>Flag Stale Guard is provided under the MIT License.</p><p>Source search is a removal aid. It cannot prove runtime behavior or replace review and tests.</p><p>Use it with your repository practices and release checks.</p>'); }
function missing() { return legal('This field guide page is missing', '<p>The page may have moved or the address may be wrong.</p><p><a href="/" data-route>Return to the flag inventory guide.</a></p>'); }
function render() { const path = routes[location.pathname] ? location.pathname : '/404.html'; app.innerHTML = `${routes[path]()}<p id="route-status" class="sr-only" aria-live="polite"></p>`; const title = path === '/demo' ? 'Demo — Flag Stale Guard' : path === '/privacy' ? 'Privacy — Flag Stale Guard' : path === '/terms' ? 'Terms — Flag Stale Guard' : path === '/404.html' ? 'Not found — Flag Stale Guard' : 'Flag Stale Guard — inspect stale release flags'; document.title = title; const heading = document.querySelector('h1'); if (heading) { heading.tabIndex = -1; heading.focus({ preventScroll: true }); document.querySelector('#route-status').textContent = heading.textContent; } document.querySelector('#reset')?.addEventListener('click', () => { localStorage.removeItem('demo:flag-stale-guard'); render(); }); document.querySelectorAll('[data-route]').forEach(link => link.addEventListener('click', e => { e.preventDefault(); history.pushState({}, '', link.getAttribute('href')); render(); window.scrollTo(0, 0); })); }
window.addEventListener('popstate', render); render();
